module.exports = {
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',

    SET_STATE: 'SET_STATE',
    RECORD_STATE: 'RECORD_STATE',
    SAVE_PRODUCT_LIST: 'SAVE_PRODUCT_LIST',
    NEW_PRODUCT_DATA: 'NEW_PRODUCT_DATA',
    DELETE_ITEM: 'DELETE_ITEM',
    REQUEST_POSTS: 'REQUEST_POSTS',
    RECEIVE_POSTS: 'RECEIVE_POSTS',
    GET_DATA_START: 'GET_DATA_START',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    TEST_DISPATCH: 'TEST_DISPATCH'
}
